// Generated by hardware/gen/outlines.py: do not edit; change the board there.
// Board origin: top-left corner, x right, y DOWN (KiCad). Units: mm.

pod_board = [80.0, 55.0, 1.6];  // w, h, thickness
pod_board_r = 2.0;
pod_board_holes = [[4.0, 4.0], [76.0, 4.0], [4.0, 51.0], [76.0, 51.0]];
pod_board_keeps = [[13.5, 41.0, 53.0, 14.0], [70.5, 22.0, 9.5, 9.0], [30.0, 0.5, 20.0, 3.0], [0.5, 12.0, 6.0, 25.0]];  // x, y, w, h
// pod_board_keeps[0]: DB-25 (J7): flange flush with the bottom edge, centred
// pod_board_keeps[1]: USB-C (J1): flush with the right edge
// pod_board_keeps[2]: Status LEDs D3-D6: top edge, facing the driver
// pod_board_keeps[3]: SWD (J5) and ELM327 (J6) headers: left edge

power_board = [110.0, 80.0, 1.6];  // w, h, thickness
power_board_r = 2.0;
power_board_holes = [[4.0, 4.0], [106.0, 4.0], [4.0, 76.0], [106.0, 76.0]];
power_board_keeps = [[28.5, 0.0, 53.0, 14.0], [2.0, 14.0, 24.0, 22.0], [9.0, 66.0, 92.0, 14.0], [96.0, 20.0, 14.0, 40.0]];  // x, y, w, h
// power_board_keeps[0]: DB-25 (J1): flange flush with the top edge
// power_board_keeps[1]: Fuse holders F1, F3: top edge, left
// power_board_keeps[2]: Terminal blocks J2-J11: bottom edge (all car-side wiring)
// power_board_keeps[3]: BTS7960 / ACS712 module headers J13, J14: right edge
